language: ruby
rvm:
  - 1.8.7
  - 1.9.3
script: "rake spec"
branches:
  only:
    - default_configure_firewall_travis
env:
  - PUPPET_VERSION=2.6.17
  - PUPPET_VERSION=2.7.19
  #- PUPPET_VERSION=3.0.1 # Breaks due to rodjek/rspec-puppet#58
notifications:
  email: false
gemfile: .gemfile
matrix:
  allow_failures:
    - rvm: 1.8.7
